apiVersion: v1
kind: Config
preferences: { }
clusters:
  
  - cluster:
      server: https://003bc566-81b4-4263-b36a-6995f1aca110.k8s.onhamravesh.ir
    name: hamravesh-c13
  
  - cluster:
      server: https://f943d869-2284-4a79-bdb3-4e29a5e3aed1.k8s.onhamravesh.ir
    name: sindad-c15
  
  - cluster:
      server: https://d581ef41-184a-48fe-9e05-d643bf4766b4.k8s.onhamravesh.ir
    name: hamravesh-c11
  
  - cluster:
      server: https://085a1ea8-01d2-4842-ab18-133eb59f9f48.k8s.onhamravesh.ir
    name: hamravesh-c5
  
contexts:
  
  - context:
      cluster: hamravesh-c13
      namespace: bluh-bluh
      user: hamravesh-console-oidc
    name: hamravesh-c13-bluh-bluh
  
  - context:
      cluster: sindad-c15
      namespace: bluh-bluh
      user: hamravesh-console-oidc
    name: sindad-c15-bluh-bluh
  
  - context:
      cluster: hamravesh-c5
      namespace: bluh-bluh
      user: hamravesh-console-oidc
    name: hamravesh-c5-bluh-bluh
  
  - context:
      cluster: hamravesh-c11
      namespace: bluh-bluh
      user: hamravesh-console-oidc
    name: hamravesh-c11-bluh-bluh
  
current-context: hamravesh-c13-bluh-bluh
users:
  - name: hamravesh-console-oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://api.console.hamravesh.ir/openid
          - --oidc-client-id=kubernetes
          - --oidc-extra-scope=openid,profile,email
        command: kubectl
