services:
  postgres:
    image: postgres:16-bookworm
    container_name: pashmak_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=pashmak_postgres
    volumes:
      - type: volume
        source: pashmak_postgres
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.2
    container_name: pashmak_redis
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - pashmak_redis:/data
  
  backend:
    image: registry.hamdocker.ir/bluh-bluh/pashamk_backend_final:latest
    container_name: pashmak_backend
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ../.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - postgres
      - redis

volumes:
  pashmak_postgres:
  pashmak_redis: