services:
  
  # this service is just for development and testing purposes and you just need to run it once
  # so currently we are not planning to use it in production
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=pashmak_minio
      - MINIO_ROOT_PASSWORD=pashmak_minio
      - MINIO_DEFAULT_BUCKETS=pashmak
    command: server /data --console-address ":9001"

  osm2pgsql:
    image: iboates/osm2pgsql:2.1.1
    environment:
      PGPASSWORD: postgres
    command: >
      osm2pgsql
      --slim
      --drop
      --cache 1000
      -d pashmak_postgres
      -U postgres
      -H postgres
      -P 5432
      https://download.geofabrik.de/asia/iran-latest.osm.pbf
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: pashmak_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pashmak_postgres
    volumes:
      - type: volume
        source: pashmak_postgres
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  pgvector:
    image: pgvector/pgvector:0.8.0-pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=google
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - type: volume
        source: pashmak_pgvector
        target: /var/lib/postgresql/data
    
  redis:
    image: redis:7.4.2
    container_name: pashmak_redis
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - pashmak_redis:/data
  
  # backend:
  #   image: registry.hamdocker.ir/bluh-bluh/pashmak-backend:1.0.4
  #   container_name: pashmak_backend
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - ../.env
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   depends_on:
  #     - postgres
  #     - redis

networks:
  minionetwork:
    driver: bridge

volumes:
  pashmak_postgres:
  pashmak_redis:
  pashmak_pgvector:
  minio_data:
    driver: local